import "./globals.css";

export const metadata = {
  title: "My DUE Test case",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
